# fastify
services:
  backend:
    build: .
    env_file:
      - ./src/conf/.env
    container_name: transcend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      # - ./node_modules:/app/node_modules
    command: npm run dev

# php
# services:
#   backend:
#     build: .
#     container_name: transcend_php
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./php-page:/data
#     command: php -S 0.0.0.0:3000 -t public
