services:
  backend:
    image: node:20-alpine
    env_file:
      - ./fastify_config/.env
    container_name: fastify-backend
    ports:
      - "3000:3000"
    volumes:
      - ../logs:/logs
      - ../backend:/app
    command: >
      bash -c ' cd /app;
        npm install;
        npm run dev;
      '
