services:
  nginx:
    image: owasp/modsecurity:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./modsecurity/crs:/etc/modsecurity/crs
    # depends_on:     # uncomment once fastiy is up and running
    #   - fastify
    depends_on:
      - vault