services:
  backend:
    image: node:20-alpine
    env_file:
      - .env
    container_name: fastify-backend
    ports:
      - "3000:3000"
    volumes:
      - ../logs:/logs
      - ../backend:/app
    working_dir: /app
    command: sh -c "npm install -g npm@11.2.0 && npm install && npm run nodemon"
